export const projects = [
    {
        title: 'Take Five Movie Database',
        thumbsrc: 'moviedb-thumb.png',
        thumbalt: 'Movie database website displaying Lord of the Rings movie poster and information.',
        excerpt: 'Movie database web application made with TMDB API.',
        description: 'Take Five is a movie database web application that pulls the most up-to-date ratings and information from The Movie Database via API calls. It is designed to allow users to view movie ratings, cast and crew and synopses, as well as save and store their favourites in their list.', 
        repo: false,
        repoLink: 'null',
        liveSite: 'https://take-five.sidney-engstrom.com',
        featuredTech: ['React', 'Chakra UI, API'],
        alltech: ['HTML5', 'CSS3', 'React', 'Chakra UI', 'TMDB API', 'Photoshop', 'Adobe XD', 'Illustrator'],
        feature: true,
        slug: 'take-five-movie-database',
        carouselImgs: ['moviedb-main.png', 'take-five-posters.png', 'coming-soon.png', 'coming-soon.png'],
        carouselAlt: ['Coming soon placeholder image'],
    },

    {
        title: 'Discover Ottawa',
        thumbsrc: 'ottawa-thumb.png',
        thumbalt: 'Tourism website displaying parliament buildings in Ottawa, Canada.',
        excerpt: 'Tourist information website for Ottawa, Ontario, Canada.',
        description: "Discover Ottawa is your gateway to exploring the city's vibrant cultural offerings. Discover local artistry in galleries and exhibitions featuring both homegrown talent and international works. Navigate the city with detailed transit information provided on the site. Whether you're drawn to art, cultural events, or the city's rich history, our platform is your essential companion for an enriching visit to Canada's capital.",
        repo: false,
        repoLink: 'null',
        liveSite: 'https://sidney-engstrom.com/discover-ottawa',
        featuredTech: ['CSS', 'JavaScript'],
        alltech: ['HTML5', 'CSS3', 'JavaScript', 'Illustrator'],
        feature: true,
        slug: 'discover-ottawa',
        carouselImgs: ['coming-soon.png', 'coming-soon.png', 'coming-soon.png', 'coming-soon.png'],
        carouselAlt: ['Coming soon placeholder image'],
    },

    {
        title: 'Vulcan Wastewater Solutions',
        thumbsrc: 'vulcan-thumb.png',
        thumbalt: 'Wastewater screen business website displaying call to action buttons and navigation.',
        excerpt: 'Heavy duty wastewater screen business website.',
        description: 'Vulcan is a heavy duty wastewater screen company website designed to inform and advise customers on the offered products and services.',
        repo: false,
        repoLink: 'null',
        liveSite: 'https://sidney-engstrom.com/vulcan/',
        featuredTech: ['JavaScript', 'SASS'],
        alltech: ['HTML5', 'SASS / SCSS', 'JavaScript'],
        feature: true,
        slug: 'vulcan',
        carouselImgs: ['coming-soon.png', 'coming-soon.png', 'coming-soon.png', 'coming-soon.png'],
        carouselAlt: ['Coming soon placeholder image'],
    },

    {
        title: 'Porter Studios',
        thumbsrc: 'coming-soon.png',
        thumbalt: 'Coming soon placeholder image.',
        excerpt: 'Wedding photography business portfolio.',
        description: 'Details coming soon.',
        repo: false,
        repoLink: 'https://github.com/htpwebdesign/porterstudio-theme',
        liveSite: 'https://porterstudio.bcitwebdeveloper.ca',
        featuredTech: ['WordPress', 'SASS', 'JavaScript'],
        alltech: ['WordPress', 'HTML5', 'PHP', 'SASS / SCSS', 'JavaScript'],
        feature: false,
        slug: 'under-construction',
        carouselImgs: ['coming-soon.png', 'coming-soon.png', 'coming-soon.png', 'coming-soon.png'],
        carouselAlt: ['Coming soon placeholder image'],
    },

    {
        title: 'Super Match',
        thumbsrc: 'match-thumb.png',
        thumbalt: 'Windows 95 desktop-themed website displaying Super Nintendo cartdige matching game.',
        excerpt: 'Retro Nintendo and Windows themed card matching game.',
        description: "Designed with an old school Windows 95 layout and old Super Nintendo cartridges instead of cards, this project was created for those craving a bit of nostalgia on the modern web.",
        repo: false,
        repoLink: 'null',
        liveSite: 'https://sidney-engstrom.com/super-match',
        featuredTech: ['CSS', 'JavaScript'],
        alltech: ['HTML5', 'CSS3', 'JavaScript', 'jQuery'],
        feature: false,
        slug: 'super-match',
        carouselImgs: ['coming-soon.png', 'coming-soon.png', 'coming-soon.png', 'coming-soon.png'],
        carouselAlt: ['Coming soon placeholder image'],
    },
]